Project Completion
Megagig/Budget-App pull request #3
Opened 2024-01-12 19:41 UTC by Megagig

**In this milestone, I did the following:**
Create Splash screen

A simple page with the name of my app and links to the sign up and log in pages.
Sign up and log in pages

The user should be able to register in the app with full name, email and password (all mandatory).
The user can log into the app using email and password.
If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).
Home page (categories page)

you can see all category
you can create a new category
Created the Transactions page

you can see all category
you can create a new category
Used Postgres as your database.

Used devise for authentication.

Deployed and accessible online.

2024-01-12 21:04 UTC, Strangeal requested changes
Hi @Megagig, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMjBkMDI3OWJlYzRhNWVlNmIyZmE5NjU5NzFlZTA0NDVjZWFhMmQ2NSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Nice *UI* design ✅ 
- Pixel Perfect Design ✅ 
- Professional `README` template ✅ 
- Correct `GitHub` workflow ✅ 
- Meaningful **Github** commits ✅ 
- Correct `.github/workflows` for linters ✅ 
- Followed *best-practices* ✅ 
- Correct **Semantics** used ✅ 
- Well structured project ✅ 

## Required Changes ♻️
🚀 **Deployment Review:**
- [ ] Fantastic work on deploying your app! 🌟 However, I noticed that the `live demo` link provided in the `README` is currently inactive. It's crucial for a seamless review process that the demo link is functional. Could you please redeploy your app and update the link in the `README` accordingly? This will ensure that reviewers can experience your application in action.

🔍 **Video Presentation Feedback:**
- [ ] Additionally, per the video presentation guide, your recording should showcase a highlighted piece of code that you're particularly proud of. This step adds a valuable dimension to your presentation by focusing on a key aspect of your implementation. I encourage you to re-record the video, keeping in mind the specific points outlined in the guide. 📹✨ This will not only enhance the quality of your presentation but also provide a deeper insight into your coding skills.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-12 21:04 UTC, Strangeal commented on app/views/devise/registrations/new.html.erb
> +    </div>
- [ ] Great progress on your implementation so far! 👏 I've had a thorough look, and I'd like to share some insights to enhance the user experience:

- **Sign Up Page:**
  - Consider moving the `Next` button from the navigation area to a more prominent position below the signup form. This adjustment can make the flow more intuitive for users.
  - Rename the `Next` button to something more descriptive like "Sign Up" or "Create Account." Clarity in button labels contributes significantly to a smoother user experience. 
  - Also, Kindly consider adding some spacing on the left and right side of the page to make your sign up form standout and more attractive.
  See below for more details:
  
<img width="443" alt="Screenshot 2024-01-12 at 20 31 00" src="https://github.com/Megagig/Budget-App/assets/107192076/6f175972-a794-4b5b-8200-236cda054adb">


Your project is impressive, but I observed that the `Next` button might be a bit confusing for users, especially without the guidance from the demo video in the `README`. Placing it prominently below the signup form with a clearer label will guide users effectively.
 
Happy coding! 😊✅🚀

2024-01-12 21:04 UTC, Strangeal commented on app/views/devise/sessions/new.html.erb
> +    </div>
- [ ] As suggested in my previous comment on the `signup` page, kindly consider making similar adjustments on the login page as it would help improve the user experience.

2024-01-13 18:22 UTC, rloterh commented on app/views/devise/registrations/new.html.erb
> +    </div>
reolved! ✔️

2024-01-13 18:51 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Megagig,  

**RoR capstone project** is complete! 🏁 Great job! Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Good job on introducing improvements on the design and presentation!
🎲 App deployed correctly!
🎲 Properly added required models, controllers, and corresponding views!
🎲 Devise correctly implemented for authentication!
🎲 Schema follow given ERD!
🎲 Awesome UI!
🎲 App is running as intended!
🎲 Added required spec test cases and are passing!
🎲 ReadMe looks great!

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

_Kindly consider my inline comments marked **[OPTIONAL]** under this review_

**You can also consider:**
You used incorrect git-flow/ GitHub flow for this project. Kindly note that a capstone project worked on by a single contributor should have merge request flow **from feature into development**. Ensuring this will easily help you manage the project workflows. Kindly note this important step for subsequent projects.

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-13 18:51 UTC, rloterh commented on app/views/devise/registrations/new.html.erb
> +<% end %>
- [ ] [OPTIONAL]
Nice job implementing requested changes, however, I think other aspects of your signup page design got affected negatively. Can we improve upon these aspects of the design?
  * The blue nav area should stretch across the entire width of the screen, with proportionate height, like seen in the template design.
  * The form fields should be similar the template design version, you can maintain the signup button you added below, but it should look bold and well-spaced accordingly.


**Your Register page:**       |  **Expected Register page:**     
:-------------------------:|:-------------------------:
<img width="800" alt="Home Page" src="https://github.com/Megagig/Budget-App/assets/12745474/52bcb4fa-426b-4700-8a8a-7be5657ee78e"> | <img width="800" alt="Home Page" src="https://github.com/Megagig/Budget-App/assets/12745474/3338e141-a039-4e4f-9e21-7a80bc6de2cc">

2024-01-13 20:45 UTC, merged